# configtx.0
# Used in the multi-org-ca setup

#   CAPABILITIES
Capabilities:
 Application: &ApplicationCapabilities
   V1_2: true
 Orderer: &OrdererCapabilities
   V1_1: true
 Channel: &ChannelCapabilities
   V1_1: true

# ORGANIZATIONS
Organizations:
 - &Ucabor
   Name: Ucabor
   ID: UcaborMSP
   MSPDir: ../ca/client/ucabor/msp
   Policies: &OrdererPolicies
     Readers:
         Type: Signature
         Rule: "OR('UcaborMSP.member')"
     Writers:
         Type: Signature
         Rule: "OR('UcaborMSP.member')"
     Admins:
         Type: Signature
         Rule: "OR('UcaborMSP.admin')"

 - &Ucab
   Name: Ucab
   ID: UcabMSP
   MSPDir: ../ca/client/ucab/msp
   Policies: &UcabPolicies
     Readers:
         Type: Signature
         Rule: "OR('UcabMSP.member')"
     Writers:
         Type: Signature
         Rule: "OR('UcabMSP.member')"
     Admins:
         Type: Signature
         Rule: "OR('UcabMSP.admin')"
   AnchorPeers:
     - Host: localhost
       Port: 7051

 - &Sce
   Name: Sce
   ID: SceMSP
   MSPDir: ../ca/client/sce/msp
   Policies: &ScePolicies
     Readers:
         Type: Signature
         Rule: "OR('SceMSP.member')"
     Writers:
         Type: Signature
         Rule: "OR('SceMSP.member')"
     Admins:
         Type: Signature
         Rule: "OR('SceMSP.admin')"
   AnchorPeers:
     - Host: localhost
       Port: 8051

 - &Ce
   Name: Ce
   ID: CeMSP
   MSPDir: ../ca/client/ce/msp
   Policies: &CePolicies
     Readers:
         Type: Signature
         Rule: "OR('CeMSP.member')"
     Writers:
         Type: Signature
         Rule: "OR('CeMSP.member')"
     Admins:
         Type: Signature
         Rule: "OR('CeMSP.admin')"
   AnchorPeers:
     - Host: localhost
       Port: 9051

#   ORDERER
Orderer: &OrdererDefaults

 OrdererType: kafka

 Addresses:
   - localhost:7050


   # Policies for Orderer
 Policies:
   Readers:
       Type: ImplicitMeta
       Rule: "ANY Readers"
   Writers:
       Type: ImplicitMeta
       Rule: "ANY Writers"
   Admins:
       Type: ImplicitMeta 
       Rule: "MAJORITY Admins"

   # BlockValidation specifies what signatures must be included in the block
   # from the orderer for the peer to validate it.
   BlockValidation:
       Type: ImplicitMeta
       Rule: "ANY Writers"

 # Batch Timeout: The amount of time to wait before creating a batch
 BatchTimeout: 2s
 Kafka:
  # Brokers: A list of Kafka brokers to which the orderer connects. Edit
  # this list to identify the brokers of the ordering service.
  # NOTE: Use IP:port notation.
  Brokers:
      - localhost:9092

 # Batch Size: Controls the number of messages batched into a block
 BatchSize:
   MaxMessageCount: 10
   AbsoluteMaxBytes: 98 MB
   PreferredMaxBytes: 512 KB



 Capabilities:
   <<: *OrdererCapabilities

Application: &ApplicationDefaults

 ACLs: &ACLsDefault
  
   # ACL policy for lscc's "getid" function
   lscc/ChaincodeExists: /Channel/Application/Readers

   # ACL policy for lscc's "getdepspec" function
   lscc/GetDeploymentSpec: /Channel/Application/Readers

   # ACL policy for lscc's "getccdata" function
   lscc/GetChaincodeData: /Channel/Application/Readers

   # ACL Policy for lscc's "getchaincodes" function
   #    lscc/GetInstantiatedChaincodes: /Channel/Application/Readers
   lscc/GetInstantiatedChaincodes: /Channel/Application/StrictAdminPolicy

   #---Query System Chaincode (qscc) function to policy mapping for access control---#

   # ACL policy for qscc's "GetChainInfo" function
   # qscc/GetChainInfo: /Channel/Application/Readers
   qscc/GetChainInfo: /Channel/Application/StrictAdminPolicy

   # ACL policy for qscc's "GetBlockByNumber" function
   qscc/GetBlockByNumber: /Channel/Application/Readers

   # ACL policy for qscc's  "GetBlockByHash" function
   qscc/GetBlockByHash: /Channel/Application/Readers

   # ACL policy for qscc's "GetTransactionByID" function
   qscc/GetTransactionByID: /Channel/Application/Readers

   # ACL policy for qscc's "GetBlockByTxID" function
   qscc/GetBlockByTxID: /Channel/Application/Readers

   #---Configuration System Chaincode (cscc) function to policy mapping for access control---#

   # ACL policy for cscc's "GetConfigBlock" function
   cscc/GetConfigBlock: /Channel/Application/Readers

   # ACL policy for cscc's "GetConfigTree" function
   cscc/GetConfigTree: /Channel/Application/Readers

   # ACL policy for cscc's "SimulateConfigTreeUpdate" function
   cscc/SimulateConfigTreeUpdate: /Channel/Application/Readers

   #---Miscellanesous peer function to policy mapping for access control---#

   # ACL policy for invoking chaincodes on peer
   peer/Propose: /Channel/Application/Writers

   # ACL policy for chaincode to chaincode invocation
   peer/ChaincodeToChaincode: /Channel/Application/Readers

   #---Events resource to policy mapping for access control###---#

   # ACL policy for sending block events
   event/Block: /Channel/Application/Readers

   # ACL policy for sending filtered block events
   event/FilteredBlock: /Channel/Application/Readers

 # Default policies
 Policies: &ApplicationDefaultPolicies
   Readers:
       Type: ImplicitMeta
       Rule: "ANY Readers"
   Writers:
       Type: ImplicitMeta
       Rule: "ANY Writers"
   Admins:
       Type: ImplicitMeta
       Rule: "MAJORITY Admins"

   StrictAdminPolicy:
       Type: ImplicitMeta
       Rule: "ANY Admins"
 Organizations:

 Capabilities:
   <<: *ApplicationCapabilities

#   CHANNEL
Channel: &ChannelDefaults
 Policies:
   Readers:
       Type: ImplicitMeta
       Rule: "ANY Readers"
   Writers:
       Type: ImplicitMeta
       Rule: "ANY Writers"
   Admins:
       Type: ImplicitMeta
       Rule: "MAJORITY Admins"

 Capabilities:

 #   PROFILES
Profiles:

 UcabOrdererGenesis:
     <<: *ChannelDefaults
     Orderer:
         <<: *OrdererDefaults
         Organizations:
             - <<: *Ucabor


     Application:
           <<: *ApplicationDefaults

           Organizations:
               - <<: *Ucab
               - <<: *Sce          
               - <<: *Ce

     Consortiums:

       UcabConsortium:
          
           Organizations:
               - <<: *Ucab
               - <<: *Sce          
               - <<: *Ce                           
                
 UcabChannel:
   <<: *ChannelDefaults
   Consortium: UcabConsortium
      
   Application:
       <<: *ApplicationDefaults
      
       Organizations:
           - <<: *Ucab
           - <<: *Sce
           - <<: *Ce
      


 
